# Generated by Django 5.2.7 on 2025-11-21 06:03

from django.db import migrations, models
import django.db.models.deletion


def ensure_departments_exist(apps, schema_editor):
    """
    Data migration: Đảm bảo có ít nhất 1 department trước khi làm field required
    Nếu chưa có department nào, tạo một department mặc định
    """
    Department = apps.get_model('appointments', 'Department')
    Appointment = apps.get_model('appointments', 'Appointment')
    
    # Kiểm tra xem có appointments nào với department=None không
    appointments_without_dept = Appointment.objects.filter(department__isnull=True)
    
    if appointments_without_dept.exists():
        # Nếu có appointments không có department, cần xử lý
        # Option 1: Tạo default department và assign
        default_dept, created = Department.objects.get_or_create(
            name='General',
            defaults={
                'icon': '🏥',
                'description': 'General department for existing appointments',
                'is_active': True
            }
        )
        
        # Assign default department cho các appointments không có department
        appointments_without_dept.update(department=default_dept)


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_department_remove_service_icon_and_more'),
    ]

    operations = [
        # Data migration: Đảm bảo không có appointments nào với department=None
        migrations.RunPython(ensure_departments_exist, migrations.RunPython.noop),
        
        # Alter field: Làm department non-nullable
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(
                help_text="Department/specialty that patient selected (e.g., 'Nhi khoa', 'Tim mạch')",
                on_delete=django.db.models.deletion.PROTECT,
                related_name='appointments',
                to='appointments.department'
            ),
        ),
    ]
