# Generated by Django 5.2.7 on 2025-11-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_make_department_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
    ]
