# Generated by Django 4.2.7 on 2025-12-02 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0005_add_department_to_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', help_text='Current status of the appointment', max_length=20),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, help_text="Doctor's diagnosis", null=True)),
                ('prescription', models.TextField(blank=True, help_text='Prescription details (medications, dosage, instructions)', null=True)),
                ('treatment_plan', models.TextField(blank=True, help_text='Treatment plan and recommendations', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional medical notes', null=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended follow-up date if needed', null=True)),
                ('vital_signs', models.JSONField(blank=True, help_text='Vital signs (blood pressure, temperature, heart rate, etc.) in JSON format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(help_text='Appointment this medical record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.appointment')),
                ('created_by', models.ForeignKey(help_text='Doctor who created this medical record', limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment'], name='medical_rec_appoint_c6c058_idx'), models.Index(fields=['created_by', '-created_at'], name='medical_rec_created_758e39_idx')],
            },
        ),
    ]
