# Generated by Django 5.2.7 on 2025-11-21 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_avatar_url_doctor_rating_doctor_total_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number (exactly 10 digits)', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Emergency contact phone must be exactly 10 digits.')]),
        ),
    ]
