# Generated by Django 5.2.7 on 2025-11-21 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_patient_emergency_contact_phone'),
        ('appointments', '0005_add_department_to_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department/specialty this doctor belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='appointments.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(help_text='Specialization (can be same as department name)', max_length=255),
        ),
    ]
