# Generated by Django 5.2.7 on 2025-11-21 14:56

from django.db import migrations


def assign_departments_to_doctors(apps, schema_editor):
    """
    Assign departments to existing doctors based on their specialization
    """
    Doctor = apps.get_model('accounts', 'Doctor')
    Department = apps.get_model('appointments', 'Department')
    
    # Mapping specialization to department name
    specialization_to_department = {
        'Nội khoa': 'Nội tiết',
        'Tim mạch': 'Tim mạch',
        'Da liễu': 'Da liễu',
        'Nhi khoa': 'Nhi khoa',
        'Sản phụ khoa': 'Sản phụ khoa',
    }
    
    # Get all doctors without department
    doctors = Doctor.objects.filter(department__isnull=True)
    
    for doctor in doctors:
        # Try to find department by specialization
        department_name = specialization_to_department.get(doctor.specialization)
        
        if department_name:
            try:
                department = Department.objects.get(name=department_name)
                doctor.department = department
                doctor.save()
            except Department.DoesNotExist:
                # If department not found, assign first available department
                first_dept = Department.objects.first()
                if first_dept:
                    doctor.department = first_dept
                    doctor.save()
        else:
            # If no mapping found, assign first available department
            first_dept = Department.objects.first()
            if first_dept:
                doctor.department = first_dept
                doctor.save()


def reverse_assign_departments(apps, schema_editor):
    """
    Reverse migration - set department to None
    """
    Doctor = apps.get_model('accounts', 'Doctor')
    Doctor.objects.all().update(department=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_department_to_doctor'),
        ('appointments', '0005_add_department_to_doctor'),
    ]

    operations = [
        migrations.RunPython(assign_departments_to_doctors, reverse_assign_departments),
    ]
