# Generated by Django 5.2.7 on 2025-11-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_make_department_required'),
        ('appointments', '0005_add_department_to_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='room',
            field=models.OneToOneField(blank=True, help_text='Room assigned to this doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='appointments.room'),
        ),
    ]
