# Azure App Service deployment configuration
# This file tells Azure how to build and deploy your app

version: 1.0

python:
  version: "3.11"
  
build:
  preBuild:
    - cd backend
    - pip install --upgrade pip
    - pip install -r requirements.txt
    
startup:
  command: backend/startup.sh
  
settings:
  - name: SCM_DO_BUILD_DURING_DEPLOYMENT
    value: "true"

