# Generated by Django 5.2.7 on 2025-11-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='insurance_info',
            new_name='insurance_id',
        ),
    ]
