"""
Django settings for myhealthcare project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

load_dotenv(BASE_DIR / '.env')
# print("BASE_DIR:", BASE_DIR)
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-only")
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost").split(",")

if os.getenv('WEBSITE_HOSTNAME'):
    ALLOWED_HOSTS.append(os.getenv('WEBSITE_HOSTNAME'))

# Database Configuration
# ======================
# IMPORTANT: Local development ALWAYS uses local database
# Production database is ONLY used when deployed
#
# Detection Logic (backward compatible):
# 1. If WEBSITE_HOSTNAME exists → Production (Azure)
# 2. If AZURE_POSTGRESQL_CONNECTIONSTRING exists AND not localhost → Production
# 3. If DATABASE_URL exists AND not localhost → Production
# 4. Otherwise → Development (Local)

# Check if running in production
# Azure automatically sets WEBSITE_HOSTNAME when deployed
IS_PRODUCTION = bool(os.getenv('WEBSITE_HOSTNAME'))

# Additional check: If connection string exists and points to remote server
# (backward compatibility for existing deployments)
azure_conn = os.getenv('AZURE_POSTGRESQL_CONNECTIONSTRING', '')
db_url = os.getenv('DATABASE_URL', '')

# Check if connection strings point to remote (not localhost)
is_remote_connection = (
    ('azure' in azure_conn.lower() or 'database.azure.com' in azure_conn) or
    ('@' in db_url and 'localhost' not in db_url and '127.0.0.1' not in db_url)
)

# Determine if production: Azure hostname OR remote connection string exists
IS_PRODUCTION = IS_PRODUCTION or (is_remote_connection and not DEBUG)

if IS_PRODUCTION:
    # PRODUCTION: Deployed environment (Azure, Heroku, etc.)
    # Use connection string from environment variables
    if os.getenv('AZURE_POSTGRESQL_CONNECTIONSTRING'):
        # Azure PostgreSQL
        DATABASES = {
            'default': dj_database_url.parse(
                os.getenv('AZURE_POSTGRESQL_CONNECTIONSTRING'),
                conn_max_age=600
            )
        }
    elif os.getenv('DATABASE_URL'):
        # Generic database URL (Heroku, Railway, etc.)
        DATABASES = {
            'default': dj_database_url.config(
                default=os.getenv('DATABASE_URL'),
                conn_max_age=600
            )
        }
    else:
        # Fallback: Should not happen in production
        raise ValueError(
            "Production environment detected but no database connection string found. "
            "Please set AZURE_POSTGRESQL_CONNECTIONSTRING or DATABASE_URL."
        )
else:
    # DEVELOPMENT: Local environment
    # ALWAYS use local database, ignore any production connection strings
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
# SECURITY WARNING: don't run with debug turned on in production!
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'corsheaders',
    "django_extensions",
    "drf_spectacular",
    # Local apps
    'apps.core',
    'apps.accounts',
    'apps.appointments',
    'apps.services',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myhealthcare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myhealthcare.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

#WHITENOISE for serving static files:
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication', #Giữ lại cho giao diện duyệt API
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # Enable browsable API interface
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Use drf-spectacular for OpenAPI schema
}

#JWT Setting
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1), #dùng để truy cập trực tiếp các API bảo mật
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), #dùng để lấy access token mới   
    'ROTATE_REFRESH_TOKENS': True, #Khi access token hết hạn, sẽ tự động lấy refresh token mới
    'BLACKLIST_AFTER_ROTATION': True, #Blacklist token cũ sau khi rotate
    'UPDATE_LAST_LOGIN': True, #Cập nhật thời gian đăng nhập gần nhất
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type'

}

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://localhost:5174",
]
if os.getenv('WEBSITE_HOSTNAME'):
    hostname = os.getenv('WEBSITE_HOSTNAME').rstrip('/')
    if hostname.startswith('https://'):
        hostname = hostname[8:]  # Loại bỏ https:// nếu có
    CORS_ALLOWED_ORIGINS.append(f"https://{hostname}")
    
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOWED_CREDENTIAL = True

SPECTACULAR_SETTINGS = {
    'TITLE': 'MyHealthCare API',
    'DESCRIPTION': 'API Documentation for MyHealthCare',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_FIELDS': True,
    
    # Cấu hình nhiều servers (domains) cho OpenAPI
    # Người dùng có thể chọn server trong Swagger UI
    'SERVERS': [
        {
            'url': 'http://127.0.0.1:8000',
            'description': 'Development server (Local)'
        },
        {
            'url': f"https://{os.getenv('WEBSITE_HOSTNAME', 'myhealthcare-api-h3amhrevg2feeab9.southeastasia-01.azurewebsites.net').rstrip('/')}",
            'description': 'Production server'
        }
    ],
    
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True, #Giữ authorization khi refresh
        'displayOperationID': True,
        'filter': True, #Cho phép lọc các endpoint theo tên
        'tagsSorter': 'alpha', #Sắp xếp các tags theo thứ tự alphabet
        'operationsSorter': 'method', #Sắp xếp operations theo HTTP method (GET, POST, PUT, PATCH, DELETE)
    },
    
    'ATUHENTICATION_WHITELIST': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'SECURITY': [{'BearerAuth': []}], #Mặc định yêu cầu JWT cho tất cả endpoints
    
    # Tags được sắp xếp theo thứ tự logic: Authentication -> User Management -> Resources -> Appointments
    'TAGS': [
        {'name': 'Authentication', 'description': 'User authentication APIs (register, login, logout)'},
        {'name': 'Accounts', 'description': 'User account management APIs (profile, doctors list)'},
        {'name': 'Departments', 'description': 'Department information APIs'},
        {'name': 'Services', 'description': 'Medical services and specialties APIs'},
        {'name': 'Appointments', 'description': 'Appointment management APIs (create, list, update, cancel)'},
    ]
}
    
    
#Email configuration

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@myhealthcare.com')

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')