# Generated by Django 5.2.7 on 2025-11-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="URL to doctor's profile picture", null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Doctor rating from 0.00 to 5.00', max_digits=3),
        ),
        migrations.AddField(
            model_name='doctor',
            name='total_reviews',
            field=models.IntegerField(default=0, help_text='Total number of reviews/ratings'),
        ),
    ]
