# Generated by Django 5.2.7 on 2025-11-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assign_department_to_existing_doctors'),
        ('appointments', '0005_add_department_to_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(
                help_text='Department/specialty this doctor belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='doctors',
                to='appointments.department'
            ),
        ),
    ]
