# Generated by Django 5.2.7 on 2025-11-20 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Room number (e.g., P101)', max_length=50, unique=True)),
                ('floor', models.IntegerField(blank=True, help_text='Floor number', null=True)),
                ('department', models.CharField(blank=True, help_text='Department/area', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Khám tổng quát)', max_length=255)),
                ('department', models.CharField(help_text='Specialty department (e.g., Nhi khoa, Tim mạch)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Service description', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Service price in VND', max_digits=10)),
                ('duration_minutes', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('icon', models.CharField(blank=True, help_text='Emoji/icon for UI display', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of appointment')),
                ('appointment_time', models.TimeField(help_text='Time of appointment')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='booked', help_text='Current status of the appointment', max_length=20)),
                ('symptoms', models.TextField(blank=True, help_text='Patient symptoms description', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for appointment', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('estimated_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated consultation fee', max_digits=10)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When appointment was cancelled', null=True)),
                ('rescheduled_from', models.JSONField(blank=True, help_text="Previous appointment date/time if rescheduled (format: {'date': 'YYYY-MM-DD', 'time': 'HH:MM'})", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor assigned to the appointment', limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient who booked the appointment', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='Room assigned for the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.room')),
                ('service', models.ForeignKey(help_text='Service/specialty for the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.service')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['-appointment_date', 'appointment_time'],
                'indexes': [models.Index(fields=['appointment_date', 'appointment_time'], name='appointment_appoint_f2c2fb_idx'), models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4449b5_idx'), models.Index(fields=['patient', 'status'], name='appointment_patient_6fe260_idx')],
            },
        ),
    ]
