# Generated by Django 5.2.7 on 2025-11-21 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Department name (e.g., 'Nhi khoa', 'Tim mạch')", max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Emoji/icon for UI display (e.g., '👶', '❤️')", max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is active')),
                ('health_examination_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Health examination fee in VND', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service assigned by doctor after consultation (optional when booking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Department/specialty that patient selected (e.g., 'Nhi khoa', 'Tim mạch')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.department'),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department/area this room belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='appointments.department'),
        ),
        migrations.AlterField(
            model_name='service',
            name='department',
            field=models.ForeignKey(help_text='Department this service belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='appointments.department'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['department'], name='appointment_departm_8008bd_idx'),
        ),
    ]
