# Generated by Django 5.2.7 on 2025-12-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(choices=[('08:00:00', '08:00'), ('08:30:00', '08:30'), ('09:00:00', '09:00'), ('09:30:00', '09:30'), ('10:00:00', '10:00'), ('10:30:00', '10:30'), ('11:00:00', '11:00'), ('11:30:00', '11:30'), ('12:00:00', '12:00'), ('12:30:00', '12:30'), ('13:00:00', '13:00'), ('13:30:00', '13:30'), ('14:00:00', '14:00'), ('14:30:00', '14:30'), ('15:00:00', '15:00'), ('15:30:00', '15:30'), ('16:00:00', '16:00'), ('16:30:00', '16:30')], help_text='Time of appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Current status of the appointment', max_length=20),
        ),
    ]
