# Generated by Django 5.2.7 on 2025-12-08 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_update_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='examination_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Examination fee from the department', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('ewallet', 'E-Wallet'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash at Clinic')], help_text='Payment method used', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('not_required', 'Not Required')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service fee from the assigned service', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total fee (service_fee + examination_fee)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['payment_status'], name='medical_rec_payment_23ccb3_idx'),
        ),
    ]
