# Generated by Django 5.2.7 on 2025-12-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_medicalrecord_examination_fee_medicalrecord_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, help_text='Department description in English', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(blank=True, help_text="Department name in English (e.g., 'Pediatrics', 'Cardiology')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, help_text='Service description in English', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, help_text='Service name in English (e.g., General Checkup)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text='Department description in Vietnamese', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text="Department name in Vietnamese (e.g., 'Nhi khoa', 'Tim mạch')", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Service description in Vietnamese', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Service name in Vietnamese (e.g., Khám tổng quát)', max_length=255),
        ),
    ]
